repositories:
  # Gitea charts, https://gitea.com/gitea/helm-chart/
  - name: gitea-charts
    url: https://dl.gitea.io/charts
  # Drone charts, https://github.com/volker-raschek/drone-charts
  - name: drone
    url: https://charts.cryptic.systems/volker.raschek
  # Docker registry chart, https://github.com/twuni/docker-registry.helm
  - name: twuni
    url: https://helm.twun.io
  # Harbor chart, https://github.com/goharbor/harbor-helm
  - name: harbor
    url: https://helm.goharbor.io
  # Argo charts, https://github.com/argoproj/argo-helm
  - name: argo
    url: https://argoproj.github.io/argo-helm

namespace: devtools

releases:
  # Git service
  - name: gitea
    chart: gitea-charts/gitea
    values:
      - ../values/gitea.yaml.gotmpl

  # Drone service
  - name: drone
    chart: drone/drone
    values:
      - ../values/drone.yaml.gotmpl

  # Drone runner service
  - name: drone-runner
    chart: drone/drone-runner
    values:
      - ../values/drone-runner.yaml.gotmpl

  # Drone gitea setup
  - name: drone-gitea-setup
    chart: ../charts/drone-gitea-setup

  # Docker registry service
  - name: registry
    chart: twuni/docker-registry
    values:
      - ../values/registry.yaml.gotmpl

  # Harbor service
  #- name: harbor
  #  chart: harbor/harbor
  #  values:
  #    - ../values/harbor.yaml.gotmpl

  # ArgoCD service
  - name: argocd
    chart: argo/argo-cd
    values:
      - ../values/argocd.yaml.gotmpl

  # ArgoCD Image Updater service
  - name: argocd-image-updater
    chart: argo/argocd-image-updater
    values:
      - ../values/argocd-image-updater.yaml.gotmpl

values:
  - ../.env.{{ .Environment.Name }}.yaml
